/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;



/**
 *
 * @author Chiko malo
 */

import java.awt.Color;
import java.io.File;
import javax.swing.JButton;
import jugador.Jugador;
import leerArchivo.LeerArchivo;
public class JuegoPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JuegoPrincipal
     */
    private Jugador jugador=new Jugador();
    private int FILS=8;
    private int COLS=8;
    JButton[][] CUADRO;
    JButton[][] jugador1;
    String[][] juego=new String[8][8];
    
    public JuegoPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        txtjugador1.setText("Turno del primer Jugador");
        txtjugador2.setText("Turno del segundo Jugador");
        setLeer();
    }
    private void setLeer(){
        File archivo =new File ("posicion.txt");
        LeerArchivo nc=new LeerArchivo();
        String[] arreglo=nc.leer(archivo);
        int x=0;
        for(int i=0;i<8;i++){
            for(int j=0;j<8;j++){
                juego[i][j]=arreglo[x];
                x++;
            /*if(arreglo[i].equals("fin")){
            System.out.println(arreglo[i]);}
                */
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnDado2 = new javax.swing.JButton();
        txtResultado2 = new javax.swing.JTextField();
        txtTurno = new javax.swing.JLabel();
        txtjugador2 = new javax.swing.JTextField();
        btnDado1 = new javax.swing.JButton();
        txtResultado1 = new javax.swing.JTextField();
        txtjugador1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 51));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setRollover(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(168, Short.MAX_VALUE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(306, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 410, 470));

        btnDado2.setBackground(new java.awt.Color(204, 0, 0));
        btnDado2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnDado2.setForeground(new java.awt.Color(255, 255, 255));
        btnDado2.setText("Tirar Dado");
        btnDado2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDado2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnDado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 110, 50));

        txtResultado2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(txtResultado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 110, -1));

        txtTurno.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(txtTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));
        getContentPane().add(txtjugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 110, -1));

        btnDado1.setBackground(new java.awt.Color(204, 0, 0));
        btnDado1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnDado1.setForeground(new java.awt.Color(255, 255, 255));
        btnDado1.setText("Tirar Dado");
        btnDado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDado1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnDado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 110, 50));

        txtResultado1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(txtResultado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 110, -1));

        txtjugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjugador1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtjugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnDado2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDado2ActionPerformed
        
        
    }//GEN-LAST:event_btnDado2ActionPerformed
    int fi=7;
    int colu=7;
    int s=0;
    private void btnDado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDado1ActionPerformed
       
    }//GEN-LAST:event_btnDado1ActionPerformed

    private void txtjugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjugador1ActionPerformed
        
    }//GEN-LAST:event_txtjugador1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JuegoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JuegoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JuegoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JuegoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JuegoPrincipal().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDado1;
    private javax.swing.JButton btnDado2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField txtResultado1;
    private javax.swing.JTextField txtResultado2;
    private javax.swing.JLabel txtTurno;
    private javax.swing.JTextField txtjugador1;
    private javax.swing.JTextField txtjugador2;
    // End of variables declaration//GEN-END:variables
}
